In [4]:
import pandas as pd

In [42]:
data = pd.read_csv('SS_cleaned.csv')
data.head(5)

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,flight_status,Weekday,cancelled,Origin Airport,Destination Airport,DEST_CODE
0,1/1/2009,OO,2554,MKE,PHL,1040,1032,1340,1320,-20,Early,Thursday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),PHL
1,1/1/2009,OO,2555,PHL,MKE,1405,1355,1530,1525,-5,Early,Thursday,No,Philadelphia International Airport (PHL),"General Mitchell International Airport, Milwau...",MKE
2,1/1/2009,OO,2556,MKE,PHL,1555,1554,1900,1843,-17,Early,Thursday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),PHL
3,1/1/2009,OO,2582,PHL,MKE,1105,1105,1230,1224,-6,Early,Thursday,No,Philadelphia International Airport (PHL),"General Mitchell International Airport, Milwau...",MKE
4,1/1/2009,OO,2620,MKE,MSN,1335,1345,1412,1419,7,Delayed,Thursday,No,"General Mitchell International Airport, Milwau...","Dane County Regional Airport, Madison (MSN)",MSN

In [43]:
dest_codes = pd.read_csv('cleaned_airport_codes.csv')
dest_codes.head()

  DEST_CODE  dest_longitude  dest_latitude
0       UTK      169.852005      11.222000
1       OCA      -80.274803      25.325399
2       PQS     -162.899994      61.934601
3       CSE     -106.928341      38.851918
4       JCY      -98.622498      30.251801

In [44]:
data.dtypes

FL_DATE                object
OP_CARRIER             object
OP_CARRIER_FL_NUM       int64
ORIGIN                 object
DEST                   object
CRS_DEP_TIME            int64
DEP_TIME                int64
CRS_ARR_TIME            int64
ARR_TIME                int64
ARR_DELAY               int64
flight_status          object
Weekday                object
cancelled              object
Origin Airport         object
Destination Airport    object
DEST_CODE              object
dtype: object

In [45]:
dest_codes.dtypes

DEST_CODE          object
dest_longitude    float64
dest_latitude     float64
dtype: object

In [46]:
# Combine the data into a single dataset.
oo_complete = pd.merge(data, dest_codes, on=["DEST_CODE", "DEST_CODE"])
oo_complete.head()

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,flight_status,Weekday,cancelled,Origin Airport,Destination Airport,DEST_CODE,dest_longitude,dest_latitude
0,1/1/2009,OO,2554,MKE,PHL,1040,1032,1340,1320,-20,Early,Thursday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),PHL,-75.241096,39.871899
1,1/1/2009,OO,2556,MKE,PHL,1555,1554,1900,1843,-17,Early,Thursday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),PHL,-75.241096,39.871899
2,2/1/2009,OO,2550,MKE,PHL,730,744,1035,1035,0,On Time,Friday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),PHL,-75.241096,39.871899
3,2/1/2009,OO,2554,MKE,PHL,1040,1041,1340,1401,21,Delayed,Friday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),PHL,-75.241096,39.871899
4,2/1/2009,OO,2556,MKE,PHL,1555,1555,1900,1847,-13,Early,Friday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),PHL,-75.241096,39.871899

In [47]:
oo_complete.to_csv('dest_update.csv', index=False)

In [32]:
data_two = pd.read_csv('dest_update.csv')
data_two.head(5)

,Unnamed: 0,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN_CODE,DEST,CRS_DEP_TIME,DEP_TIME,CRS_ARR_TIME,ARR_TIME,...,flight_status,Weekday,cancelled,Origin Airport,Destination Airport,DEST_CODE,dest_longitude,dest_latitude,Unnamed: 19,ORIGIN_CODE.1
0,0,1/1/2009,OO,2554,MKE,PHL,1040,1032,1340,1320,...,Early,Thursday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),MKE,-87.896599,42.947201,NaN,NaN
1,1,1/1/2009,OO,2556,MKE,PHL,1555,1554,1900,1843,...,Early,Thursday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),MKE,-87.896599,42.947201,NaN,NaN
2,2,1/1/2009,OO,2620,MKE,MSN,1335,1345,1412,1419,...,Delayed,Thursday,No,"General Mitchell International Airport, Milwau...","Dane County Regional Airport, Madison (MSN)",MKE,-87.896599,42.947201,NaN,NaN
3,3,1/1/2009,OO,2625,MKE,MSN,1605,1600,1643,1643,...,On Time,Thursday,No,"General Mitchell International Airport, Milwau...","Dane County Regional Airport, Madison (MSN)",MKE,-87.896599,42.947201,NaN,NaN
4,4,1/1/2009,OO,2638,MKE,GRR,1333,1332,1515,1515,...,On Time,Thursday,No,"General Mitchell International Airport, Milwau...","Gerald R. Ford International Airport, Grand Ra...",MKE,-87.896599,42.947201,NaN,NaN

In [54]:
ori = pd.read_csv('dest_update_ii.csv')
ori.head(5)

,Unnamed: 0,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,flight_status,Weekday,cancelled,Origin Airport,Destination Airport,DEST_CODE,dest_longitude,dest_latitude,ORIGIN_CODE
0,0,1/1/2009,OO,2554,MKE,PHL,1040,1032,1340,1320,-20,Early,Thursday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),PHL,-75.241096,39.871899,MKE
1,1,1/1/2009,OO,2556,MKE,PHL,1555,1554,1900,1843,-17,Early,Thursday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),PHL,-75.241096,39.871899,MKE
2,2,2/1/2009,OO,2550,MKE,PHL,730,744,1035,1035,0,On Time,Friday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),PHL,-75.241096,39.871899,MKE
3,3,2/1/2009,OO,2554,MKE,PHL,1040,1041,1340,1401,21,Delayed,Friday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),PHL,-75.241096,39.871899,MKE
4,4,2/1/2009,OO,2556,MKE,PHL,1555,1555,1900,1847,-13,Early,Friday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),PHL,-75.241096,39.871899,MKE

In [55]:
ori_codes = pd.read_csv('cleaned_airport_codes_ii.csv')
ori_codes.head()

  ORIGIN_CODE  origin_longitude  origin_latitude
0         UTK        169.852005        11.222000
1         OCA        -80.274803        25.325399
2         PQS       -162.899994        61.934601
3         CSE       -106.928341        38.851918
4         JCY        -98.622498        30.251801

In [56]:
# Combine the data into a single dataset.
merge = pd.merge(ori, ori_codes, on=["ORIGIN_CODE", "ORIGIN_CODE"])
merge.head()

,Unnamed: 0,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,CRS_ARR_TIME,ARR_TIME,...,Weekday,cancelled,Origin Airport,Destination Airport,DEST_CODE,dest_longitude,dest_latitude,ORIGIN_CODE,origin_longitude,origin_latitude
0,0,1/1/2009,OO,2554,MKE,PHL,1040,1032,1340,1320,...,Thursday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),PHL,-75.241096,39.871899,MKE,-87.896599,42.947201
1,1,1/1/2009,OO,2556,MKE,PHL,1555,1554,1900,1843,...,Thursday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),PHL,-75.241096,39.871899,MKE,-87.896599,42.947201
2,2,2/1/2009,OO,2550,MKE,PHL,730,744,1035,1035,...,Friday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),PHL,-75.241096,39.871899,MKE,-87.896599,42.947201
3,3,2/1/2009,OO,2554,MKE,PHL,1040,1041,1340,1401,...,Friday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),PHL,-75.241096,39.871899,MKE,-87.896599,42.947201
4,4,2/1/2009,OO,2556,MKE,PHL,1555,1555,1900,1847,...,Friday,No,"General Mitchell International Airport, Milwau...",Philadelphia International Airport (PHL),PHL,-75.241096,39.871899,MKE,-87.896599,42.947201

In [58]:
merge.to_csv('complete.csv', index=False)